spring:
  application:
    name: user-center
  datasource:
    username: usercenter
    password: YBAAEsPiCHfPpsWa
    url: jdbc:mysql://localhost:3306/usercenter
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
  servlet:
      context-path: "/api"
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除字段名(deleted为实体类属性名称)
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0
